"""
CYNIC CLI — `probes` command (L4 SelfProber proposals).
"""
from __future__ import annotations

import os
import sys

from cynic.interfaces.cli.utils import (
    _CYNIC_DIR,
    _api_get,
    _bar,
    _c,
    _read_json,
)

# Probe dimension → color
_PROBE_DIM_COLOR = {
    "QTABLE":   "orange",
    "ESCORE":   "yellow",
    "CONFIG":   "cyan",
    "RESIDUAL": "dim",
}


def cmd_probes() -> None:
    """
    Show self-improvement proposals generated by the L4 SelfProber.

    SelfProber analyzes QTable, EScore, and Residual patterns on
    EMERGENCE_DETECTED events and produces concrete improvement recommendations.

    Usage: python -m cynic.interfaces.cli probes [status]
      status: PENDING (default) | all | APPLIED | DISMISSED
    """
    args = sys.argv[2:]
    filter_status = (args[0].upper() if args else "PENDING")

    # Try API first
    path = "/self-probes" + ("" if filter_status == "PENDING" else f"?status={filter_status}")
    data = _api_get(path)

    if data is None:
        # File fallback: read ~/.cynic/self_proposals.json directly
        _SELF_PROPOSALS = os.path.join(_CYNIC_DIR, "self_proposals.json")
        raw = _read_json(_SELF_PROPOSALS)
        if not isinstance(raw, list):
            return
        all_p = raw
        proposals = (
            [p for p in all_p if p.get("status") == filter_status]
            if filter_status != "ALL"
            else all_p
        )
        api_ok = False
    else:
        proposals = data.get("proposals", [])
        api_ok = True

    if not proposals:
        return

    "API mode" if api_ok else _c("orange", "file mode (server offline)")

    for p in proposals:
        dim     = p.get("dimension", "?")
        p.get("target", "?")
        p.get("recommendation", "")
        cur     = float(p.get("current_value", 0))
        sug     = float(p.get("suggested_value", 0))
        sev     = float(p.get("severity", 0))
        float(p.get("proposed_at", 0))
        p.get("probe_id", "?")
        p.get("pattern_type", "?")
        p.get("status", "PENDING")

        _PROBE_DIM_COLOR.get(dim, "white")

        _bar(sev * 100, max_score=100.0, width=8)

        if cur != sug:
            pass

    # Summary stats
    if data and "stats" in data:
        data["stats"]
