"""
CYNIC CLI — `probes` command (L4 SelfProber proposals).
"""
from __future__ import annotations

import os
import sys

from cynic.cli.utils import (
    _CYNIC_DIR,
    _api_get, _read_json,
    _c, _bar, _ago,
)

# Probe dimension → color
_PROBE_DIM_COLOR = {
    "QTABLE":   "orange",
    "ESCORE":   "yellow",
    "CONFIG":   "cyan",
    "RESIDUAL": "dim",
}


def cmd_probes() -> None:
    """
    Show self-improvement proposals generated by the L4 SelfProber.

    SelfProber analyzes QTable, EScore, and Residual patterns on
    EMERGENCE_DETECTED events and produces concrete improvement recommendations.

    Usage: python -m cynic.cli probes [status]
      status: PENDING (default) | all | APPLIED | DISMISSED
    """
    args = sys.argv[2:]
    filter_status = (args[0].upper() if args else "PENDING")

    # Try API first
    path = f"/self-probes" + ("" if filter_status == "PENDING" else f"?status={filter_status}")
    data = _api_get(path)

    if data is None:
        # File fallback: read ~/.cynic/self_proposals.json directly
        _SELF_PROPOSALS = os.path.join(_CYNIC_DIR, "self_proposals.json")
        raw = _read_json(_SELF_PROPOSALS)
        if not isinstance(raw, list):
            print()
            print(_c("gray", "  *sniff* No self-improvement proposals yet."))
            print(_c("dim", "  Run server and trigger a judgment to generate probes."))
            print()
            return
        all_p = raw
        proposals = (
            [p for p in all_p if p.get("status") == filter_status]
            if filter_status != "ALL"
            else all_p
        )
        api_ok = False
    else:
        proposals = data.get("proposals", [])
        api_ok = True

    if not proposals:
        print()
        print(_c("green", f"  *tail wag* No {filter_status.lower()} proposals."))
        print(_c("dim",  f"  {'API' if api_ok else 'file'} mode — probes generated on EMERGENCE_DETECTED"))
        print()
        return

    print()
    mode_note = "API mode" if api_ok else _c("orange", "file mode (server offline)")
    print(_c("bold", f"  CYNIC SELF-PROBES — {len(proposals)} {filter_status.lower()}"))
    print(f"  {_c('dim', mode_note)}")
    print()

    for p in proposals:
        dim     = p.get("dimension", "?")
        target  = p.get("target", "?")
        rec     = p.get("recommendation", "")
        cur     = float(p.get("current_value", 0))
        sug     = float(p.get("suggested_value", 0))
        sev     = float(p.get("severity", 0))
        ts      = float(p.get("proposed_at", 0))
        pid     = p.get("probe_id", "?")
        pattern = p.get("pattern_type", "?")
        status  = p.get("status", "PENDING")

        dim_col  = _PROBE_DIM_COLOR.get(dim, "white")
        sev_col  = "red" if sev >= 0.7 else ("orange" if sev >= 0.4 else "yellow")
        stat_col = "green" if status == "APPLIED" else ("dim" if status == "DISMISSED" else "yellow")

        sev_bar = _bar(sev * 100, max_score=100.0, width=8)

        print(
            f"  {_c(dim_col, f'[{dim}]')}"
            f"  {pid}"
            f"  {_ago(ts)}"
            f"  pattern={_c('dim', pattern)}"
        )
        print(
            f"  target={_c('bold', target[:50])}"
            f"  severity={_c(sev_col, sev_bar)}"
            f"  status={_c(stat_col, status)}"
        )
        print(f"  {rec[:100]}")
        if cur != sug:
            print(f"  {_c('dim', f'current={cur:.4f} → suggested={sug:.4f}')}")
        print()

    # Summary stats
    if data and "stats" in data:
        s = data["stats"]
        print(
            _c("dim",
               f"  total={s.get('proposed_total',0)}"
               f"  pending={s.get('pending',0)}"
               f"  applied={s.get('applied',0)}"
               f"  dismissed={s.get('dismissed',0)}"
            )
        )
    print()
