"""
CYNIC Bootstrap — Self-initialization.

When CYNIC starts, it automatically:
1. Creates version structure (.version/, VERSION, CHANGELOG.md)
2. Registers API routers
3. Initializes Docker manager
4. Sets up TUI panels
5. Starts health monitoring

The organism bootstraps itself. No manual setup needed.
"""
from __future__ import annotations

import asyncio
import logging
from pathlib import Path
from datetime import datetime

logger = logging.getLogger(__name__)

CYNIC_ROOT = Path(__file__).parent.parent.parent.parent


class CynicBootstrap:
    """Bootstrap CYNIC's self-infrastructure."""

    def __init__(self):
        self.version_dir = CYNIC_ROOT / ".version"
        self.version_file = self.version_dir / "VERSION"
        self.changelog_file = self.version_dir / "CHANGELOG.md"
        self.migrations_dir = self.version_dir / "migrations"

    async def initialize(self) -> dict:
        """
        Bootstrap CYNIC completely.

        Returns:
            Status dict of what was initialized
        """
        status = {}

        # 1. Create version structure
        status["version_structure"] = await self._init_version_structure()

        # 2. Create initial migration
        status["initial_migration"] = await self._create_initial_migration()

        # 3. Create default docker-compose env
        status["docker_env"] = await self._create_docker_env()

        # 4. Initialize gitignore patterns
        status["gitignore"] = await self._init_gitignore()

        logger.info(f"CYNIC Bootstrap complete: {status}")
        return status

    async def _init_version_structure(self) -> dict:
        """Create .version/ directory and VERSION file."""
        try:
            # Create directories
            self.version_dir.mkdir(exist_ok=True)
            self.migrations_dir.mkdir(exist_ok=True)

            # Create VERSION file if not exists
            if not self.version_file.exists():
                self.version_file.write_text("1.0.0\n")
                logger.info("Created VERSION file: 1.0.0")

            # Create CHANGELOG.md if not exists
            if not self.changelog_file.exists():
                changelog = """# CYNIC Changelog

All notable changes to this project will be documented in this file.

## [1.0.0] - 2026-02-20

### Added
- Initial Python kernel bootstrap
- Self-orchestration layer (docker, versioning, monitoring)
- TUI command center for orchestration
- Auto-initialization (this file)

### Changed
- Consolidated architecture (eliminated Node.js legacy)
- Unified docker-compose.yml

### Notes
- CYNIC now self-manages builds, deployments, and versions
- No external orchestration tools (n8n) needed
- Everything is controllable from the TUI
"""
                self.changelog_file.write_text(changelog)
                logger.info("Created CHANGELOG.md")

            return {
                "version_dir_created": True,
                "migrations_dir_created": True,
                "version_file_created": not self.version_file.exists(),
                "changelog_created": not self.changelog_file.exists(),
            }

        except Exception as e:
            logger.exception("Version structure initialization failed")
            return {"error": str(e)}

    async def _create_initial_migration(self) -> dict:
        """Create V001__initial.sql if not exists."""
        try:
            migration_file = self.migrations_dir / "V001__initial.sql"

            if not migration_file.exists():
                migration = """-- CYNIC v1.0.0 Initial Schema
-- Auto-generated by bootstrap
-- Created: 2026-02-20

CREATE SCHEMA IF NOT EXISTS cynic;

-- Version table (bootstrap)
CREATE TABLE IF NOT EXISTS cynic.versions (
    id SERIAL PRIMARY KEY,
    version VARCHAR(50) NOT NULL UNIQUE,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    notes TEXT
);

INSERT INTO cynic.versions (version, notes)
VALUES ('1.0.0', 'Initial schema')
ON CONFLICT (version) DO NOTHING;

-- Judgment storage (bootstrap-minimal)
CREATE TABLE IF NOT EXISTS cynic.judgments (
    id UUID PRIMARY KEY,
    q_score FLOAT NOT NULL,
    verdict VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_judgments_created ON cynic.judgments(created_at DESC);

-- Q-Table (learning)
CREATE TABLE IF NOT EXISTS cynic.qtable (
    state_key VARCHAR(255) NOT NULL,
    action VARCHAR(50) NOT NULL,
    q_value FLOAT NOT NULL DEFAULT 0.0,
    visits INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (state_key, action)
);

CREATE INDEX idx_qtable_visits ON cynic.qtable(visits DESC);
"""
                migration_file.write_text(migration)
                logger.info("Created initial migration: V001__initial.sql")

                return {
                    "migration_created": True,
                    "file": str(migration_file),
                }

            return {"migration_exists": True}

        except Exception as e:
            logger.exception("Migration creation failed")
            return {"error": str(e)}

    async def _create_docker_env(self) -> dict:
        """Create .env file for docker-compose if not exists."""
        try:
            env_file = CYNIC_ROOT / ".env"

            if not env_file.exists():
                env_content = """# CYNIC Docker Environment
# Auto-generated by bootstrap

# Database
POSTGRES_USER=cynic
POSTGRES_PASSWORD=cynic_dev_secure_change_in_prod
POSTGRES_DB=cynic_py

# Logging
LOG_LEVEL=INFO

# Ollama
OLLAMA_KEEP_ALIVE=24h

# Node (for reference/legacy)
NODE_ENV=development
"""
                env_file.write_text(env_content)
                logger.info("Created .env file (change passwords in production!)")

                return {
                    "env_file_created": True,
                    "warning": "Change POSTGRES_PASSWORD in production",
                }

            return {"env_file_exists": True}

        except Exception as e:
            logger.exception(".env creation failed")
            return {"error": str(e)}

    async def _init_gitignore(self) -> dict:
        """Add orchestration files to .gitignore."""
        try:
            gitignore_file = CYNIC_ROOT / ".gitignore"

            patterns_to_add = [
                # Version files (local only)
                ".version/migrations/*.sql",
                ".version/*.lock",
                # Docker artifacts
                ".docker/",
                # Environment
                ".env.local",
                ".env.*.local",
                # Orchestration logs
                "orchestration.log",
                "deployments.log",
            ]

            if gitignore_file.exists():
                content = gitignore_file.read_text()

                for pattern in patterns_to_add:
                    if pattern not in content:
                        content += f"\n{pattern}"

                gitignore_file.write_text(content)
                logger.info("Updated .gitignore with orchestration patterns")

                return {"gitignore_updated": True}

            return {"gitignore_exists": True}

        except Exception as e:
            logger.exception(".gitignore update failed")
            return {"error": str(e)}


async def bootstrap_cynic() -> bool:
    """
    Bootstrap CYNIC on startup.

    Called from api/server.py lifespan.
    """
    logger.info("🧬 CYNIC Bootstrap starting...")

    bootstrap = CynicBootstrap()
    status = await bootstrap.initialize()

    logger.info(f"🧬 CYNIC Bootstrap complete: {status}")
    return True
